const fs = require('fs');
const c = fs.readFileSync('index.html', 'utf8');
console.log('=== VERIFICACIONES FINALES ===');
console.log('1. form-docente-fields:', c.includes('form-docente-fields'));
console.log('2. form-estudiante-fields:', c.includes('form-estudiante-fields'));
console.log('3. nu-identificacion:', c.includes('nu-identificacion'));
console.log('4. nu-sede:', c.includes('nu-sede'));
console.log('5. nu-nombre-doc:', c.includes('nu-nombre-doc'));
console.log('6. nu-nombre-est:', c.includes('nu-nombre-est'));
console.log('7. switchUserView:', c.includes('switchUserView'));
console.log('8. cargarUsuarios function:', c.includes('async function cargarUsuarios()'));
console.log('9. renderUsuariosTabla:', c.includes('function renderUsuariosTabla'));
console.log('10. admin-modal es pagina:', c.includes('Panel Admin como P'));
console.log('11. toggleAdmin redirige:', c.includes('Redirige al panel admin'));
console.log('12. boton flotante eliminado:', !c.includes('position:fixed; bottom:20px; right:20px;'));
console.log('13. sidebar usa switchMainTab admin:', c.includes("switchMainTab('admin')"));
console.log('14. tabMap tiene admin:', c.includes("'admin': ['admin-modal']"));
console.log('15. NO switchUserForm viejo:', !c.includes('window.switchUserForm'));
console.log('16. guardarUsuario maneja 2 tipos:', c.includes('maestro_estudiantes') && c.includes('nu-nombre-doc'));
console.log('17. NO botones CERRAR en admin:', !c.includes('onclick="toggleAdmin()"'));
