name: Supabase Keep Alive
on:
  schedule:
    - cron: '0 12 * * *' # Ejecutar todos los días a las 12:00 UTC (mañana en Colombia)
  workflow_dispatch: # Permite ejecución manual desde GitHub Actions

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase API
        run: |
          curl -i -X GET "https://txnecdeccianklqqyrav.supabase.co/rest/v1/eval_estudiantes_notas?select=grado&limit=1" \
          -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4bmVjZGVjY2lhbmtscXF5cmF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY0MDQzMDIsImV4cCI6MjA5MTk4MDMwMn0.e2ybyt2Y8yHsZwRC-MZqi_qK525-CWpk-huQcQy-icM" \
          -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4bmVjZGVjY2lhbmtscXF5cmF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY0MDQzMDIsImV4cCI6MjA5MTk4MDMwMn0.e2ybyt2Y8yHsZwRC-MZqi_qK525-CWpk-huQcQy-icM"
